### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by webstersx01** [Y300-0100/android_device_samsung_kanas3gnfcxx#2]
Does It compatibld with SM-G355H, not HN.

**Comment by webstersx01** [comment]
Compatible*

**Comment by Y300-0100** [comment]
Yes.

**Comment by webstersx01** [comment]
I'm ported cyanogenmod 11 and install it on SM-G355H, but it does'nt bootable, what is?

**Comment by Y300-0100** [comment]
I can't even build stock kernel from source provided by Samsung. Once I got working logcat and cm11boot logo using stock kernel but there couldn't boot because some missing display drivers.  So i don't working on it because my hard drive died. You can use my device tree to try because it's close and I probably missed something.
